global:
  scrape_interval: 4s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          [
            'gateway:3000',
            'users:3000',
            'email:3000',
            'videos:3000',
            'likes:3000',
          ]
